### ISSUE TITLE
`inherit` statements get coloured incorrectly

### ISSUE THREAD

**Issue by rossburton** [savoirfairelinux/vscode-bitbake#54]
If a recipe `inherit`s multiple classes then the first is coloured differently to the rest.

![Screenshot 2023-11-06 at 16 40 08](https://github.com/savoirfairelinux/vscode-bitbake/assets/32394/f66f21ff-d385-45f5-a419-f876b180ef79)

**Comment by WilsonZiweiWang** [comment]
Fixed with https://github.com/savoirfairelinux/vscode-bitbake/commit/5d6838645b53f64f97fe69bd0a026161f004e936
