### ISSUE TITLE
Escaped quotes confused highlighter

### ISSUE THREAD

**Issue by rossburton** [savoirfairelinux/vscode-bitbake#55]
I get that this is somewhat pathological, but this line in a shell function confuses the parser/highlighter:

```
bbnote Executing ACLOCAL=\"$ACLOCAL\" autoreconf -Wcross --verbose --install --force ${EXTRA_AUTORECONF} $acpaths
```

(as seen in `autotools.bbclass`)

![Screenshot 2023-11-06 at 16 43 58](https://github.com/savoirfairelinux/vscode-bitbake/assets/32394/36d98732-cc49-4d99-86cd-3f870d7ca7ee)

**Comment by WilsonZiweiWang** [comment]
Fixed with https://github.com/savoirfairelinux/vscode-bitbake/pull/90
